'use client';
import { FormEvent, useEffect, useRef, useState } from 'react';
import { formatDeadline, initialOrganiserForm, ORGANISER_DECLARATIONS, OrganiserForm, validateOrganiserForm } from '@/lib/squad-invite-organiser-form';

type Stage='email'|'otp'|'existing'|'details'|'review'|'receipt';
type ExistingRequest={publicReference:string;teamName:string;status:string};
const roleLabels: Record<string,string>={coach_or_club_representative:'Coach or authorised club representative',team_manager:'Team manager',parent_representative:'Parent representative authorised by the team'};
const declarationLabels: Record<(typeof ORGANISER_DECLARATIONS)[number],string>={authorityAccepted:'I confirm that I am an adult authorised to create and share this Squad Invite for the named team.',deliveryRecipientAccepted:'I confirm that the delivery recipient has agreed to receive and distribute the completed team package.',independentParticipationAccepted:'I understand that each parent decides independently whether to participate.',staffReviewAccepted:'I understand that Emblem staff must approve this request before it can be shared.'};

export default function OrganiserStart(){
 const [stage,setStage]=useState<Stage>('email'); const [csrf,setCsrf]=useState(''); const [email,setEmail]=useState(''); const [code,setCode]=useState(''); const [error,setError]=useState(''); const [fieldErrors,setFieldErrors]=useState<ReturnType<typeof validateOrganiserForm>>([]); const [cooldown,setCooldown]=useState(0); const [form,setForm]=useState<OrganiserForm>(initialOrganiserForm); const [receipt,setReceipt]=useState<{publicReference:string;created:boolean}|null>(null); const [submitting,setSubmitting]=useState(false); const submissionKey=useRef<string>(); const [existingRequests,setExistingRequests]=useState<ExistingRequest[]>([]);
 useEffect(()=>{void fetch('/api/squad-invite-organiser-auth/context',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(x=>setCsrf(x.csrfToken)).catch(()=>setError('This controlled-pilot request is unavailable.'));},[]);
 useEffect(()=>{if(!cooldown)return;const id=setInterval(()=>setCooldown(x=>Math.max(0,x-1)),1000);return()=>clearInterval(id);},[cooldown]);
 const send=async()=>{setError('');const r=await fetch('/api/squad-invite-organiser-auth/request-code',{method:'POST',headers:{'Content-Type':'application/json','X-Emblem-CSRF':csrf},body:JSON.stringify({email})});if(!r.ok&&r.status!==429){setError('We could not process that request. Please try again.');return;}setCooldown(60);setStage('otp');};
 const verify=async()=>{setError('');const r=await fetch('/api/squad-invite-organiser-auth/verify-code',{method:'POST',headers:{'Content-Type':'application/json','X-Emblem-CSRF':csrf},body:JSON.stringify({email,code,returnTo:'/squad-invite/start'})});if(!r.ok){setError('That verification code was not accepted.');return;}const b=await r.json().catch(()=>null) as {existingRequests?:ExistingRequest[]}|null;const existing=b?.existingRequests??[];if(existing.length>0){setExistingRequests(existing);setStage('existing');return;}setStage('details');};
 const review=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const errors=validateOrganiserForm(form);setFieldErrors(errors);if(errors.length){setError('Check the highlighted fields before reviewing your request.');requestAnimationFrame(()=>document.getElementById(`organiser-${errors[0].field}`)?.focus());return;}setError('');setStage('review');};
 const submit=async()=>{if(submitting)return;setSubmitting(true);setError('');submissionKey.current??=crypto.randomUUID();try{const r=await fetch('/api/squad-invite-requests',{method:'POST',headers:{'Content-Type':'application/json','X-Emblem-CSRF':csrf},body:JSON.stringify({...form,expectedSquadSize:Number(form.expectedSquadSize),deadlineAt:`${form.deadlineAt}T12:00:00.000Z`,submissionKey:submissionKey.current})});const b=await r.json().catch(()=>null);if(!r.ok){setError(b?.error??'The request could not be submitted.');return;}setReceipt(b);setStage('receipt');}finally{setSubmitting(false);}};
 const field=(key:keyof OrganiserForm,value:string|boolean)=>{setForm(x=>({...x,[key]:value}));setFieldErrors(x=>x.filter(item=>item.field!==key));};
 const message=(key:keyof OrganiserForm)=>fieldErrors.find(item=>item.field===key)?.message;
 return <main className="mx-auto min-h-screen max-w-2xl px-5 py-12"><p className="text-sm font-bold uppercase tracking-widest text-orange-600">Controlled pilot · payment disabled</p><h1 className="mt-3 text-4xl font-bold">Start your Squad Invite</h1><p className="mt-4">One team link lets each parent privately create their child&apos;s card. No child information or roster is requested from the organiser.</p>
 {stage==='email'&&<section className="mt-8 rounded-2xl border bg-white p-6"><label className="block font-semibold">Organiser email<input className="mt-2 block w-full rounded-xl border p-3" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><p className="mt-3 text-sm">Email verification confirms that you control this email address. Your declared team role is reviewed separately by Emblem.</p><button type="button" className="mt-5 w-full rounded-xl bg-orange-600 p-3 font-bold text-white" disabled={!csrf||!email.includes('@')} onClick={send}>Send verification code</button></section>}
 {stage==='otp'&&<section className="mt-8 rounded-2xl border bg-white p-6"><label className="block font-semibold">Verification code<input className="mt-2 block w-full rounded-xl border p-3" inputMode="numeric" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,8))}/></label><button type="button" className="mt-5 w-full rounded-xl bg-orange-600 p-3 font-bold text-white" disabled={!/^\d{6,8}$/.test(code)} onClick={verify}>Verify email</button><div className="mt-4 flex gap-4"><button type="button" disabled={cooldown>0} onClick={send}>{cooldown?`Resend in ${cooldown}s`:'Resend code'}</button><button type="button" onClick={()=>{setStage('email');setCode('');}}>Change email</button></div><p className="mt-3 text-sm">Verification proves email control only. It does not verify club authority, employment, DBS status or safeguarding clearance.</p></section>}
 {stage==='existing'&&<section className="mt-8 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Your existing Squad Invite{existingRequests.length>1?'s':''}</h2><p className="mt-3">You already have {existingRequests.length===1?'a request':`${existingRequests.length} requests`} under this email.</p><ul className="mt-4 grid gap-3">{existingRequests.map(r=><li key={r.publicReference} className="rounded-xl border p-4"><strong>{r.teamName}</strong><p className="mt-1 text-sm">Reference {r.publicReference} · Status: {r.status.replaceAll('_',' ')}</p><a className="mt-2 inline-block font-bold text-orange-600" href={`/squad-invite/manage/${r.publicReference}`}>View request status</a></li>)}</ul><button type="button" className="mt-5 w-full rounded-xl border-2 border-orange-600 p-3 font-bold text-orange-600" onClick={()=>setStage('details')}>Start a new Squad Invite for a different team</button></section>}
 {stage==='details'&&<form className="mt-8 grid gap-4 rounded-2xl border bg-white p-6" onSubmit={review} noValidate><h2 className="text-2xl font-bold">Organiser and team details</h2>{error&&<ErrorSummary error={error} errors={fieldErrors}/>}<Text id="organiser-organiserName" label="Organiser full name" value={form.organiserName} set={v=>field('organiserName',v)} error={message('organiserName')}/><label>Declared role<select id="organiser-organiserRole" className="mt-1 block w-full rounded-xl border p-3" value={form.organiserRole} onChange={e=>field('organiserRole',e.target.value)} aria-invalid={Boolean(message('organiserRole'))}><option value="coach_or_club_representative">Coach or authorised club representative</option><option value="team_manager">Team manager</option><option value="parent_representative">Parent representative authorised by the team</option></select></label><Text id="organiser-teamName" label="Team/club display name" value={form.teamName} set={v=>field('teamName',v)} error={message('teamName')}/><Text id="organiser-ageGroup" label="Football age group" value={form.ageGroup} set={v=>field('ageGroup',v)} error={message('ageGroup')}/><Text id="organiser-expectedSquadSize" label="Estimated squad size" type="number" min="1" value={form.expectedSquadSize} set={v=>field('expectedSquadSize',v)} error={message('expectedSquadSize')}/><Text id="organiser-deadlineAt" label="Proposed invitation deadline" type="date" value={form.deadlineAt} set={v=>field('deadlineAt',v)} error={message('deadlineAt')}/><Text id="organiser-deliveryRecipientName" label="Delivery-recipient name" value={form.deliveryRecipientName} set={v=>field('deliveryRecipientName',v)} error={message('deliveryRecipientName')}/><Text id="organiser-deliveryRecipientRole" label="Delivery-recipient role" value={form.deliveryRecipientRole} set={v=>field('deliveryRecipientRole',v)} error={message('deliveryRecipientRole')}/><Check id="organiser-ukDeliveryConfirmed" checked={form.ukDeliveryConfirmed} onChange={v=>field('ukDeliveryConfirmed',v)} text="I confirm that completed cards will be delivered together to this UK delivery recipient." error={message('ukDeliveryConfirmed')}/><p className="text-sm">The full delivery address is requested only after approval. Optional badge and coach-card details can be reviewed with staff; no roster upload is accepted.</p><Checks form={form} field={field} message={message}/><button type="submit" className="rounded-xl bg-orange-600 p-3 font-bold text-white">Review request</button></form>}
 {stage==='review'&&<section className="mt-8 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Review your request</h2>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}<dl className="mt-4 grid gap-3"><Summary label="Declared role" value={roleLabels[form.organiserRole]}/><Summary label="Team name" value={form.teamName}/><Summary label="Football age group" value={form.ageGroup}/><Summary label="Estimated squad size" value={form.expectedSquadSize}/><Summary label="Proposed deadline" value={formatDeadline(form.deadlineAt)}/><Summary label="Delivery recipient" value={`${form.deliveryRecipientName}, ${form.deliveryRecipientRole}`}/><Summary label="Consolidated UK delivery" value="Confirmed"/></dl><h3 className="mt-5 font-bold">Your confirmations</h3><ul className="mt-2 grid gap-2">{ORGANISER_DECLARATIONS.map(key=><li key={key}>✓ {declarationLabels[key]}</li>)}</ul><div className="mt-5 flex flex-col gap-3 sm:flex-row"><button type="button" onClick={()=>{setError('');setStage('details');}}>Edit request</button><button type="button" disabled={submitting} className="flex-1 rounded-xl bg-orange-600 p-3 font-bold text-white disabled:opacity-60" onClick={submit}>{submitting?'Submitting…':'Submit for staff review'}</button></div></section>}
 {stage==='receipt'&&receipt&&<section className="mt-8 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Your Squad Invite request has been received.</h2><p className="mt-3">Reference: <strong>{receipt.publicReference}</strong></p><p className="mt-3">We aim to review controlled-pilot requests within two business days. The receipt notification is stored in a disabled test outbox; no email has been sent.</p><a className="mt-5 inline-block font-bold text-orange-600" href={`/squad-invite/manage/${receipt.publicReference}`}>View request status</a></section>}{stage!=='details'&&stage!=='review'&&error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}<p className="mt-8 text-sm">Payments and public profiles remain disabled during this test. Parent participation becomes available only after staff approval and organiser setup.</p></main>;
}
function ErrorSummary({error,errors}:{error:string;errors:ReturnType<typeof validateOrganiserForm>}){return <div role="alert" tabIndex={-1} className="rounded-xl bg-red-50 p-3 text-red-800"><p className="font-bold">{error}</p><ul className="mt-1 list-disc pl-5">{errors.map(item=><li key={item.field}>{item.message}</li>)}</ul></div>}
function Text({id,label,value,set,type='text',min,error}:{id:string;label:string;value:string;set:(v:string)=>void;type?:string;min?:string;error?:string}){const errorId=`${id}-error`;return <label htmlFor={id}>{label}<input id={id} className="mt-1 block w-full rounded-xl border p-3" type={type} min={min} value={value} onChange={e=>set(e.target.value)} aria-invalid={Boolean(error)} aria-describedby={error?errorId:undefined}/>{error&&<span id={errorId} className="mt-1 block text-sm text-red-700">{error}</span>}</label>}
function Check({id,checked,onChange,text,error}:{id:string;checked:boolean;onChange:(v:boolean)=>void;text:string;error?:string}){const errorId=`${id}-error`;return <label htmlFor={id} className="flex gap-3"><input id={id} type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} aria-invalid={Boolean(error)} aria-describedby={error?errorId:undefined}/><span>{text}{error&&<span id={errorId} className="mt-1 block text-sm text-red-700">{error}</span>}</span></label>}
function Checks({form,field,message}:{form:OrganiserForm;field:(k:keyof OrganiserForm,v:boolean)=>void;message:(k:keyof OrganiserForm)=>string|undefined}){return <fieldset className="grid gap-3"><legend className="font-bold">Required declarations</legend>{ORGANISER_DECLARATIONS.map(key=><Check key={key} id={`organiser-${key}`} checked={form[key]} onChange={v=>field(key,v)} text={declarationLabels[key]} error={message(key)}/>)}</fieldset>}
function Summary({label,value}:{label:string;value:string}){return <div><dt className="font-semibold">{label}</dt><dd>{value}</dd></div>}
