'use client';
import { useEffect,useMemo,useState } from 'react';

type Stage='email'|'otp'|'details'|'review'|'receipt';
const initial={organiserName:'',organiserRole:'coach_or_club_representative',teamName:'',ageGroup:'',expectedSquadSize:'',deadlineAt:'',deliveryRecipientName:'',deliveryRecipientRole:'',ukDeliveryConfirmed:false,authorityAccepted:false,deliveryRecipientAccepted:false,independentParticipationAccepted:false,staffReviewAccepted:false,badgeAuthorityAccepted:false};

export default function OrganiserStart(){
 const [stage,setStage]=useState<Stage>('email'); const [csrf,setCsrf]=useState(''); const [email,setEmail]=useState(''); const [code,setCode]=useState(''); const [error,setError]=useState(''); const [cooldown,setCooldown]=useState(0); const [form,setForm]=useState(initial); const [receipt,setReceipt]=useState<{publicReference:string;created:boolean}|null>(null);
 useEffect(()=>{void fetch('/api/squad-invite-organiser-auth/context',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(x=>setCsrf(x.csrfToken)).catch(()=>setError('This controlled-pilot request is unavailable.'));},[]);
 useEffect(()=>{if(!cooldown)return;const id=setInterval(()=>setCooldown(x=>Math.max(0,x-1)),1000);return()=>clearInterval(id);},[cooldown]);
 const valid=useMemo(()=>form.organiserName.trim()&&form.teamName.trim()&&form.ageGroup.trim()&&Number(form.expectedSquadSize)>0&&form.deadlineAt&&form.deliveryRecipientName.trim()&&form.deliveryRecipientRole.trim()&&form.ukDeliveryConfirmed&&form.authorityAccepted&&form.deliveryRecipientAccepted&&form.independentParticipationAccepted&&form.staffReviewAccepted,[form]);
 const send=async()=>{setError('');const r=await fetch('/api/squad-invite-organiser-auth/request-code',{method:'POST',headers:{'Content-Type':'application/json','X-Emblem-CSRF':csrf},body:JSON.stringify({email})});if(!r.ok&&r.status!==429){setError('We could not process that request. Please try again.');return;}setCooldown(60);setStage('otp');};
 const verify=async()=>{setError('');const r=await fetch('/api/squad-invite-organiser-auth/verify-code',{method:'POST',headers:{'Content-Type':'application/json','X-Emblem-CSRF':csrf},body:JSON.stringify({email,code,returnTo:'/squad-invite/start'})});if(!r.ok){setError('That verification code was not accepted.');return;}setStage('details');};
 const submit=async()=>{setError('');const submissionKey=crypto.randomUUID();const r=await fetch('/api/squad-invite-requests',{method:'POST',headers:{'Content-Type':'application/json','X-Emblem-CSRF':csrf},body:JSON.stringify({...form,expectedSquadSize:Number(form.expectedSquadSize),deadlineAt:new Date(form.deadlineAt).toISOString(),submissionKey})});const b=await r.json().catch(()=>null);if(!r.ok){setError(b?.error??'The request could not be submitted.');return;}setReceipt(b);setStage('receipt');};
 const field=(key:keyof typeof initial,value:string|boolean)=>setForm(x=>({...x,[key]:value}));
 return <main className="mx-auto min-h-screen max-w-2xl px-5 py-12"><p className="text-sm font-bold uppercase tracking-widest text-orange-600">Controlled pilot · payment disabled</p><h1 className="mt-3 text-4xl font-bold">Start your Squad Invite</h1><p className="mt-4">One team link lets each parent privately create their child&apos;s card. No child information or roster is requested from the organiser.</p>
 {stage==='email'&&<section className="mt-8 rounded-2xl border bg-white p-6"><label className="block font-semibold">Organiser email<input className="mt-2 block w-full rounded-xl border p-3" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><p className="mt-3 text-sm">Email verification confirms that you control this email address. Your declared team role is reviewed separately by Emblem.</p><button className="mt-5 w-full rounded-xl bg-orange-600 p-3 font-bold text-white" disabled={!csrf||!email.includes('@')} onClick={send}>Send verification code</button></section>}
 {stage==='otp'&&<section className="mt-8 rounded-2xl border bg-white p-6"><label className="block font-semibold">Verification code<input className="mt-2 block w-full rounded-xl border p-3" inputMode="numeric" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,8))}/></label><button className="mt-5 w-full rounded-xl bg-orange-600 p-3 font-bold text-white" disabled={!/^\d{6,8}$/.test(code)} onClick={verify}>Verify email</button><div className="mt-4 flex gap-4"><button disabled={cooldown>0} onClick={send}>{cooldown?`Resend in ${cooldown}s`:'Resend code'}</button><button onClick={()=>{setStage('email');setCode('');}}>Change email</button></div><p className="mt-3 text-sm">Verification proves email control only. It does not verify club authority, employment, DBS status or safeguarding clearance.</p></section>}
 {stage==='details'&&<section className="mt-8 grid gap-4 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Organiser and team details</h2><Text label="Organiser full name" value={form.organiserName} set={v=>field('organiserName',v)}/><label>Declared role<select className="mt-1 block w-full rounded-xl border p-3" value={form.organiserRole} onChange={e=>field('organiserRole',e.target.value)}><option value="coach_or_club_representative">Coach or authorised club representative</option><option value="team_manager">Team manager</option><option value="parent_representative">Parent representative authorised by the team</option></select></label><Text label="Team/club display name" value={form.teamName} set={v=>field('teamName',v)}/><Text label="Football age group" value={form.ageGroup} set={v=>field('ageGroup',v)}/><Text label="Estimated squad size" type="number" value={form.expectedSquadSize} set={v=>field('expectedSquadSize',v)}/><Text label="Proposed invitation deadline" type="date" value={form.deadlineAt} set={v=>field('deadlineAt',v)}/><Text label="Delivery-recipient name" value={form.deliveryRecipientName} set={v=>field('deliveryRecipientName',v)}/><Text label="Delivery-recipient role" value={form.deliveryRecipientRole} set={v=>field('deliveryRecipientRole',v)}/><p className="text-sm">The full delivery address is requested only after approval. Optional badge and coach-card details can be reviewed with staff; no roster upload is accepted.</p><Checks form={form} field={field}/><button className="rounded-xl bg-orange-600 p-3 font-bold text-white" disabled={!valid} onClick={()=>setStage('review')}>Review request</button></section>}
 {stage==='review'&&<section className="mt-8 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Review your request</h2><dl className="mt-4 grid gap-2"><div><dt>Team</dt><dd>{form.teamName} · {form.ageGroup}</dd></div><div><dt>Organiser</dt><dd>{form.organiserName}</dd></div><div><dt>Estimated participation</dt><dd>{form.expectedSquadSize}</dd></div><div><dt>Deadline</dt><dd>{form.deadlineAt}</dd></div><div><dt>Delivery recipient</dt><dd>{form.deliveryRecipientName}, {form.deliveryRecipientRole}</dd></div></dl><div className="mt-5 flex gap-3"><button onClick={()=>setStage('details')}>Edit</button><button className="flex-1 rounded-xl bg-orange-600 p-3 font-bold text-white" onClick={submit}>Submit for Emblem review</button></div></section>}
 {stage==='receipt'&&receipt&&<section className="mt-8 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Your Squad Invite request has been received.</h2><p className="mt-3">Reference: <strong>{receipt.publicReference}</strong></p><p className="mt-3">We aim to review controlled-pilot requests within two business days. The receipt notification is stored in a disabled test outbox; no email has been sent.</p><a className="mt-5 inline-block font-bold text-orange-600" href={`/squad-invite/manage/${receipt.publicReference}`}>View request status</a></section>}{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}<p className="mt-8 text-sm">Payments, public profiles and parent participation remain disabled during this checkpoint.</p></main>;
}
function Text({label,value,set,type='text'}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label>{label}<input className="mt-1 block w-full rounded-xl border p-3" type={type} value={value} onChange={e=>set(e.target.value)} required/></label>}
function Checks({form,field}:{form:typeof initial;field:(k:keyof typeof initial,v:boolean)=>void}){return <div className="grid gap-3">{[['authorityAccepted','I confirm that I am an adult authorised to create and share this Squad Invite for the named team.'],['deliveryRecipientAccepted','I confirm that the delivery recipient has agreed to receive and distribute the completed team package.'],['independentParticipationAccepted','I understand that each parent decides independently whether to participate.'],['staffReviewAccepted','I understand that Emblem staff must approve this request before it can be shared.']] .map(([k,t])=><label key={k} className="flex gap-3"><input type="checkbox" checked={Boolean(form[k as keyof typeof initial])} onChange={e=>field(k as keyof typeof initial,e.target.checked)}/><span>{t}</span></label>)}</div>}
