import { readFileSync } from 'fs';import { describe,expect,it } from 'vitest';
const read=(p:string)=>readFileSync(p,'utf8');
describe('Squad Invite MVP organiser, staff and preview contracts',()=>{
 it('gates every new production surface behind the closed runtime flag',()=>{for(const p of ['src/app/squad-invite/start/page.tsx','src/app/squad-invite/manage/[reference]/page.tsx','src/app/api/squad-invite-requests/route.ts','src/app/api/squad-invite-requests/[reference]/activate/route.ts','src/app/api/staff/squad-invites/[id]/approve/route.ts'])expect(read(p)).toContain('isSquadInviteMvpEnabled');});
 it('blocks parent participation and every real Squad Invite surface when the runtime flag is closed',()=>{const middleware=read('src/middleware.ts');const scope=read('src/lib/squad-invite-preview-safety.ts');expect(middleware).toContain('realSquadInviteSurface && !isSquadInviteMvpEnabled()');expect(middleware).toContain('isRealSquadInviteSurfacePath(path)');expect(scope).toContain("path.startsWith('/api/squad-invite')");});
 it('implements one code-based contract for first-time and returning organiser authentication',()=>{const ui=read('src/app/squad-invite/start/OrganiserStart.tsx');const request=read('src/app/api/squad-invite-organiser-auth/request-code/route.ts');const verify=read('src/app/api/squad-invite-organiser-auth/verify-code/route.ts');expect(ui).toContain('setCooldown(60)');expect(ui).toContain('Send verification code');expect(ui).toContain('Verification code');expect(request).toContain('If the address can receive a code');expect(request).toContain("'otp-request'");expect(request).toContain('signInWithOtp');expect(request).toContain('shouldCreateUser:true');expect(request).toContain('emailRedirectTo:undefined');expect(verify).toContain("'otp-verify'");expect(verify).toContain("verifyOtp({email,token:code,type:'email'})");expect(verify).toContain("returnTo:'/squad-invite/start'");});
 it('keeps organiser authentication redirects fixed and rejects client-selected return destinations',()=>{const ui=read('src/app/squad-invite/start/OrganiserStart.tsx');const verify=read('src/app/api/squad-invite-organiser-auth/verify-code/route.ts');expect(ui).toContain("returnTo:'/squad-invite/start'");expect(verify).toContain("returnTo:'/squad-invite/start'");expect(verify).not.toContain('safeSquadInviteReturnPath');expect(verify).not.toMatch(/redirect\s*\(/);expect(verify).not.toMatch(/body\?\.returnTo|body\.returnTo/);});
 it('describes enabled parent participation accurately while keeping payments and profiles disabled',()=>{const ui=read('src/app/squad-invite/start/OrganiserStart.tsx');expect(ui).toContain('Payments and public profiles remain disabled during this test. Parent participation becomes available only after staff approval and organiser setup.');expect(ui).not.toContain('parent participation remain disabled during this checkpoint');});
 it('does not imply that the enabled parent journey can collect payment',()=>{const join=read('src/app/squad-invite/join/JoinSquadInvite.tsx');expect(join).toContain('Each parent or guardian builds and commits individually.');expect(join).toContain('Payment requests are not active during this test.');expect(join).not.toContain('builds and pays individually');});
 it('rejects prohibited and unknown request fields through a typed allowlist',()=>{const route=read('src/app/api/squad-invite-requests/route.ts');expect(route).toContain('Object.keys(body).some');for(const forbidden of ['childName','photo','roster','dateOfBirth','school','medical','parentContacts'])expect(route).not.toContain(`'${forbidden}'`);});
 it('keeps delivery setup organiser-owned, CSRF checked and absent from email rendering',()=>{const route=read('src/app/api/squad-invite-requests/[reference]/activate/route.ts');const email=read('src/lib/squad-invite-email-preview.ts');expect(route).toContain('hasValidSquadInviteCsrf');expect(route).toContain('r.organiser_profile_id!==user.id');expect(email).not.toMatch(/delivery_address|courierContact|postcode/);});
 it('enforces reviewer and approver permissions on server routes',()=>{const review=read('src/app/api/staff/squad-invites/[id]/review/route.ts');const approve=read('src/app/api/staff/squad-invites/[id]/approve/route.ts');expect(review).toContain("'squad_invite_reviewer'");expect(review).toContain("'squad_invite_approver'");expect(approve).toContain("'squad_invite_approver'");});
 it('contains all twenty isolated synthetic review states and no service imports',()=>{const preview=read('src/app/dev/squad-invite-preview/SquadInvitePreview.tsx');for(const state of ['homepage-entry','builder-entry','start','organiser-email','organiser-otp','organiser-form','organiser-declarations','organiser-review','request-received','staff-queue','staff-review','changes-requested','organiser-correction','approval-foundation','approval-email','setup-required','delivery-setup','link-ready','notification-failure','feature-disabled'])expect(preview).toContain(`'${state}'`);expect(preview).not.toMatch(/supabase|resend\.com|shopify/i);});
 it('documents static-only migration status without claiming DPIA approval',()=>{const dpia=read('docs/compliance/childrens-dpia-v0.1.md');expect(dpia).toContain('STATICALLY VERIFIED ONLY — NOT EXECUTED');expect(dpia).toContain('DPIA remains unapproved');});
});
