'use client';

import { useMemo, useState } from 'react';
import Image from 'next/image';
import './preview.css';
import './badge.css';

const states = [
  ['create', 'Create Squad Invite'], ['approval', 'Awaiting staff approval'], ['staff', 'Staff approval'],
  ['publish', 'Publish and reusable link'], ['share', 'WhatsApp share preview'], ['invite', 'Parent invitation'],
  ['verify', 'New parent verification'], ['resume', 'Returning parent'], ['builder', 'One-child builder'],
  ['permissions', 'Permissions'], ['saved', 'Card saved'], ['closed', 'Closed/deadline'],
  ['dashboard', 'Organiser dashboard'], ['squad', 'Squad price unlocked'], ['coach-pending', 'Coach card pending'],
  ['coach-config', 'Coach card configuration'], ['fulfilment', 'Distribution view'], ['links', 'Link exception states'],
] as const;
type PreviewState = typeof states[number][0];

const deadline = new Date(Date.now() + 7 * 86400000);
const dateText = deadline.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

function Pill({ children, tone = 'green' }: { children: React.ReactNode; tone?: 'green' | 'amber' | 'grey' | 'red' }) {
  return <span className={`si-pill ${tone}`}>{children}</span>;
}
function Metric({ value, label }: { value: string; label: string }) {
  return <div className="si-metric"><strong>{value}</strong><span>{label}</span></div>;
}
function PreviewNotice() {
  return <p className="si-preview-notice">Preview only — no payment will be taken.</p>;
}
function BrandHeader() {
  return <header className="si-brand"><span className="si-header-spacer" aria-hidden="true"/><div className="si-brand-lockup"><Image src="/embm-nav.png" width={108} height={32} style={{ height: 'auto' }} alt="Emblem"/><span>Squad Invite</span></div><span className="si-help-label">Help</span></header>;
}
function ClubBadge({ className = '' }: { className?: string }) {
  return <span className={`si-badge-crop ${className}`} role="img" aria-label="Ashton Juniors approved fictional badge"><Image src="/templates/hollinwood-red/club-badge-ashton.png" width={1024} height={1536} priority alt=""/></span>;
}
function ProductCard({ coach = false, generic = false }: { coach?: boolean; generic?: boolean }) {
  const initials = coach ? 'CJ' : generic ? '★' : 'MR';
  const name = coach ? 'COACH JORDAN' : generic ? 'YOUR PLAYER' : 'MAYA R.';
  const detail = coach ? 'HEAD COACH' : generic ? '00 · YOUR POSITION' : '08 · MIDFIELDER';
  const label = coach ? 'Coach card artwork' : generic ? 'Generic player card example with no child identity' : 'Synthetic private player card artwork';
  return <div className={`si-product-card${generic ? ' generic' : ''}`} aria-label={label}><div className="si-card-shine"/><ClubBadge className="si-card-badge"/><span className="si-card-kicker">ASHTON JUNIORS</span><div className="si-card-avatar" aria-hidden="true">{initials}</div><strong>{name}</strong><small>{detail}</small><b>EMBLEM</b></div>;
}

export default function SquadInvitePreview() {
  const [state, setState] = useState<PreviewState>('create');
  const [linkCopied, setLinkCopied] = useState(false);
  const index = states.findIndex(([id]) => id === state);
  const go = (offset: number) => setState(states[(index + offset + states.length) % states.length][0]);
  const reviewerAction = (label: string, next: PreviewState) => <button className="si-reviewer-action" onClick={() => setState(next)}><span>Reviewer control</span>{label} →</button>;

  const screen = useMemo(() => {
    switch (state) {
      case 'create': return <><Hero eyebrow="Organiser setup" title="Create a Squad Invite" copy="One team link. Each parent creates their child’s card individually. Parents pay after the team price is confirmed."/><CreationFields/><Check text="I am an adult authorised to create and share this Squad Invite."/><button className="si-primary" onClick={() => setState('approval')}>Send for staff approval <span>→</span></button></>;
      case 'approval': return <><Hero eyebrow="Draft saved" title="Waiting for Emblem review" copy="The invitation cannot be shared until an authorised staff member approves it."/><StatusSteps active={1}/><Pill tone="amber">Awaiting staff approval</Pill>{reviewerAction('Open staff review', 'staff')}</>;
      case 'staff': return <><Hero eyebrow="Controlled pilot safeguard" title="Review Squad Invite" copy="A lightweight staff check before the organiser can share the invitation."/><StaffChecklist/><div className="si-actions"><button className="si-secondary" onClick={() => setState('approval')}>Return for changes</button><button className="si-primary" onClick={() => setState('publish')}>Approve Squad Invite</button></div></>;
      case 'publish': return <><Hero eyebrow="Approved" title="Squad Invite link ready" copy="Share one link in the existing parent WhatsApp group. It contains no child or parent information."/><div className="si-link-ready"><span className="si-icon">✓</span><div><strong>Reusable invitation link created</strong><span>Credential details stay hidden from the organiser view.</span></div></div><div className="si-actions"><button className="si-secondary" onClick={() => setLinkCopied(true)}>{linkCopied ? 'Link copied' : 'Copy link'}</button><button className="si-primary" onClick={() => setState('share')}>Share to WhatsApp</button></div><div className="si-quiet-actions"><button onClick={() => setState('links')}>Pause invitation</button><button onClick={() => setState('links')}>Replace link</button></div></>;
      case 'share': return <><Hero eyebrow="WhatsApp preview" title="Ready to share" copy="No contacts or group membership are sent to Emblem."/><div className="si-phone"><div className="si-phone-top">Ashton Juniors parents <span>•••</span></div><div className="si-message"><b>Coach Jordan</b><p>Ashton Juniors U10 has opened an Emblem Squad Invite. Create your child’s personalised sporting card privately by {dateText}. Participation is optional. Create your card now and pay after the team price is confirmed.</p><div className="si-share-card"><ClubBadge/><span><b>Join Ashton Juniors U10</b><small>2 more completed cards unlock £18.99 · One team delivery</small></span></div></div></div>{reviewerAction('Preview parent opening link', 'invite')}</>;
      case 'invite': return <><div className="si-invite-hero"><div><ClubBadge className="si-club-badge"/><Hero eyebrow="Ashton Juniors · Under 10" title="Make their moment iconic." copy="Create your child’s card now. Pay after the team price is confirmed."/></div><ProductCard generic/></div><Progress/><p className="si-estimate">Estimated squad size: 15</p><div className="si-trust"><b>Private. Secure. Parent controlled.</b><span>Participation is optional. No participant list or child photograph is public.</span></div><Delivery/><PreviewNotice/><button className="si-primary" onClick={() => setState('verify')}>Create your child’s card <span>→</span></button></>;
      case 'verify': return <><Hero eyebrow="Private parent session" title="Verify your email" copy="We’ll send a one-time code so you can return safely to this invitation."/><label className="si-field">Email address<input defaultValue="alex.taylor@example.test" type="email"/></label><button className="si-primary" onClick={() => setState('builder')}>Send verification code <span>→</span></button>{reviewerAction('Preview returning parent', 'resume')}</>;
      case 'resume': return <><Hero eyebrow="Welcome back" title="Resume your private card" copy="Your existing card was found. The shared team link never exposes your private builder."/><Pill>Private card resumed</Pill><button className="si-primary" onClick={() => setState('builder')}>Continue card <span>→</span></button></>;
      case 'builder': return <><Hero eyebrow="Private builder · Step 2 of 4" title="Create their card" copy="This information is not visible to Coach Jordan or other parents."/><div className="si-builder-layout"><ProductCard/><BuilderControls/></div><p className="si-help">Synthetic initials only. No real photograph is used. Controls demonstrate the intended journey and do not save data.</p><button className="si-primary" onClick={() => setState('permissions')}>Review before saving <span>→</span></button></>;
      case 'permissions': return <><Hero eyebrow="Parent permissions" title="Before you save the card" copy="Please confirm the following so Emblem can prepare your child’s personalised card."/><div className="si-permissions"><Check text="I am the child’s parent/guardian or have permission to submit their details."/><Check text="I have permission to use this photograph on the printed card."/><Check text="I understand the cards will be delivered together to Coach Jordan."/><Check text="I understand I am not paying today. I will receive a payment request after the team price is confirmed."/></div><button className="si-primary" onClick={() => setState('saved')}>Save my child’s card <span>→</span></button></>;
      case 'saved': return <><div className="si-success-mark">✓</div><Hero eyebrow="Card completed" title="Your child’s card is saved" copy="You have not been charged. When the invitation closes, Emblem will confirm the final team price and send you a payment request."/><Pill>Card design saved</Pill><Delivery detail="Your card will be delivered with the team order to Coach Jordan after payment and production."/><button className="si-primary" onClick={() => setState('invite')}>Done</button>{reviewerAction('Return to team invitation', 'invite')}</>;
      case 'closed': return <><Hero eyebrow="Invitation closed" title="New card starts are closed" copy="Parents who began before the deadline may finish their card during the 24-hour grace period."/><Pill tone="grey">Team price confirms after grace</Pill><Progress/><PreviewNotice/></>;
      case 'dashboard': return <><Hero eyebrow="Organiser dashboard" title="Ashton Juniors U10" copy="Aggregate progress only. No parent list, payment details or child photographs."/><div className="si-dashboard-strip"><div><span>Progress to squad price</span><strong>8 of 10</strong></div><div className="si-ring" aria-label="80 percent of squad-price target completed">80%</div></div><progress className="si-native-progress" value="8" max="10" aria-label="8 of 10 cards completed for squad price">8 of 10</progress><div className="si-grid"><Metric value="8" label="completed cards"/><Metric value="10" label="squad-price target"/><Metric value="15" label="estimated squad size"/><Metric value="£21.99" label="current price"/></div><div className="si-milestones"><b>Squad price: 2 more completed cards needed</b><span>Free coach card: Confirmed after 10 parents pay</span></div><StatusSteps active={2}/><Delivery organiser/>{reviewerAction('Preview 10 completed cards', 'squad')}</>;
      case 'squad': return <><div className="si-celebrate">SQUAD PRICE UNLOCKED</div><Hero eyebrow="Team price confirmed" title="£18.99 per card" copy="Ten distinct completed eligible cards freeze the squad price."/><div className="si-grid"><Metric value="10" label="completed cards"/><Metric value="£18.99" label="confirmed unit price"/></div><div className="si-milestones"><b>Squad price unlocked: £18.99 per card</b><span>Free coach card: Waiting for 10 successful payments</span></div><PreviewNotice/></>;
      case 'coach-pending': return <><div className="si-coach-layout"><ProductCard coach/><div><Hero eyebrow="Separate milestone" title="Free coach card pending" copy="In the future live product, the free coach card is confirmed after ten successful, non-refunded player payments."/><div className="si-grid"><Metric value="10" label="completed cards"/><Metric value="Not active" label="payment requests in preview"/></div><Pill tone="amber">Waiting for 10 successful payments</Pill></div></div></>;
      case 'coach-config': return <><Hero eyebrow="Adult card · proposed" title="Configure coach card" copy="This card never creates a child profile or Player OS account."/><div className="si-builder-layout"><ProductCard coach/><FormRows rows={['Coach Jordan', 'Role: Head coach', 'Team: Ashton Juniors U10', 'Design: Emblem black']}/></div><Pill tone="amber">Synthetic configuration · not production eligible</Pill>{reviewerAction('Preview fulfilment view', 'fulfilment')}</>;
      case 'fulfilment': return <><Hero eyebrow="Consolidated fulfilment" title="One team package" copy="One standard UK team delivery is included. Paid cards are individually sealed for private distribution."/><div className="si-box-visual"><b>EMBLEM</b><span>ASHTON JUNIORS U10</span><small>15 sealed card envelopes · one organiser delivery</small></div><div className="si-package"><b>Package SI-014</b><span>For the parent/guardian of Maya R. — No. 8</span><Pill>Sealed</Pill></div><p className="si-help">No email, phone, address, permission record, internal child ID or NFC claim secret appears here.</p></>;
      case 'links': return <><Hero eyebrow="Reusable link controls" title="This invitation is unavailable" copy="Invalid, expired, paused and revoked links use the same privacy-preserving response."/><div className="si-unavailable">Link unavailable</div><div className="si-link-grid">{[['Invalid', 'Unavailable'], ['Expired', 'Unavailable'], ['Paused', 'Unavailable'], ['Revoked', 'Unavailable'], ['Replaced', 'Old link unavailable']].map(([a, b]) => <div key={a}><b>{a} link</b><span>{b}</span></div>)}</div><button className="si-secondary" onClick={() => setState('publish')}>Replace shared link</button><p className="si-help">Existing private cards survive replacement without retaining public-link authority.</p></>;
    }
  }, [state, linkCopied]);

  return <main className="si-preview"><div className="si-shell"><div className="si-preview-bar"><b>Synthetic product preview</b><span>· No database · No payments · No real child data</span></div><aside className="si-reviewer-nav" aria-label="Reviewer navigation — synthetic preview only"><strong>Reviewer navigation — synthetic preview only</strong><div><button onClick={() => go(-1)} aria-label="Previous synthetic preview state">←</button><select value={state} onChange={(e) => setState(e.target.value as PreviewState)} aria-label="Choose synthetic preview state">{states.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><button onClick={() => go(1)} aria-label="Next synthetic preview state">→</button></div></aside><div className="si-product-surface"><BrandHeader/><section className="si-screen" aria-label={states[index][1]}>{screen}</section><footer className="si-footer"><span className="si-footer-identity">© Emblem</span><span>Privacy</span><span>Safety</span><span>Support</span></footer></div></div></main>;
}

function Hero({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <header className="si-header"><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></header>; }
function FormRows({ rows }: { rows: string[] }) { return <div className="si-rows">{rows.map((row) => <div key={row}>{row}</div>)}</div>; }
function Check({ text }: { text: string }) { return <label className="si-check"><input type="checkbox" defaultChecked/><span>{text}</span></label>; }
function Delivery({ detail = 'Paid cards arrive in one team package for Coach Jordan to distribute to participating families.', organiser = false }: { detail?: string; organiser?: boolean }) { return <div className="si-delivery"><span className="si-icon">↗</span><div><b>{organiser ? 'One standard UK team delivery is included' : 'Delivered together to your organiser'}</b><span>{detail}</span></div></div>; }
function Progress() { return <><div className="si-grid"><Metric value="8 of 10" label="cards completed"/><Metric value="£21.99" label="current price"/></div><progress className="si-native-progress" value="8" max="10" aria-label="8 of 10 cards completed for squad price">8 of 10</progress><p className="si-progress-copy">2 more completed cards unlock the £18.99 squad price</p><Pill tone="amber">Free coach card confirmed after 10 parents pay</Pill></>; }
function StatusSteps({ active }: { active: number }) { return <div className="si-steps">{['Created', 'Staff approval', 'Shared', 'Closed'].map((x, i) => <span className={i <= active ? 'done' : ''} key={x}>{x}</span>)}</div>; }
function CreationFields() { return <div className="si-form-grid"><label>Team<input defaultValue="Ashton Juniors U10"/></label><label>Age group<input defaultValue="Under 10"/></label><label>Organiser<input defaultValue="Coach Jordan"/></label><label>Invitation deadline<input defaultValue={dateText}/></label><label>Estimated squad size<input defaultValue="15" inputMode="numeric"/></label></div>; }
function BuilderControls() { return <div className="si-builder-controls"><button className="si-upload" type="button"><span aria-hidden="true">＋</span><b>Upload or replace photograph</b><small>Synthetic preview only</small></button><label>Display name<input defaultValue="Maya Reed"/></label><div className="si-two-fields"><label>Squad number<input defaultValue="8"/></label><label>Quantity<input defaultValue="1"/></label></div><label>Position<select defaultValue="Midfielder"><option>Midfielder</option><option>Goalkeeper</option><option>Defender</option><option>Forward</option></select></label><label>Card design<select defaultValue="Emblem black"><option>Emblem black</option><option>Club colour</option></select></label></div>; }
function StaffChecklist() { return <div className="si-staff-checklist">{['Organiser declaration received', 'Team and club identity appears credible', 'Badge-use authority recorded or pending', 'Delivery recipient provided', 'Deadline is reasonable', 'Duplicate campaign check completed', 'No child roster uploaded'].map((item) => <div key={item}><span aria-hidden="true">✓</span>{item}</div>)}</div>; }
