'use client';

import { useMemo, useState } from 'react';
import Image from 'next/image';
import './preview.css';
import './badge.css';

const states = [
  ['homepage-entry','Homepage Teams entry'],['builder-entry','Builder entry choice'],['start','Start Squad Invite'],
  ['organiser-email','Organiser email'],['organiser-otp','OTP verification'],['organiser-form','Organiser/team form'],
  ['organiser-declarations','Separate declarations'],['organiser-review','Review and submit'],['request-received','Request received'],
  ['staff-queue','Staff Squad Invites queue'],['staff-review','Review Squad Invite'],['changes-requested','Changes requested'],
  ['organiser-correction','Correction and resubmission'],['approval-foundation','Approval'],['approval-email','Approval email'],
  ['setup-required','Approved setup required'],['delivery-setup','Delivery setup'],['link-ready','Link ready'],
  ['notification-failure','Disabled notification failure'],['feature-disabled','Feature disabled'],
] as const;
type PreviewState = string;

const deadline = new Date(Date.now() + 7 * 86400000);
const dateText = deadline.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

function Pill({ children, tone = 'green' }: { children: React.ReactNode; tone?: 'green' | 'amber' | 'grey' | 'red' }) {
  return <span className={`si-pill ${tone}`}>{children}</span>;
}
function Metric({ value, label }: { value: string; label: string }) {
  return <div className="si-metric"><strong>{value}</strong><span>{label}</span></div>;
}
function PreviewNotice() {
  return <p className="si-preview-notice">Preview only — no payment will be taken.</p>;
}
function BrandHeader() {
  return <header className="si-brand"><span className="si-header-spacer" aria-hidden="true"/><div className="si-brand-lockup"><Image src="/embm-nav.png" width={108} height={32} style={{ height: 'auto' }} alt="Emblem"/><span>Squad Invite</span></div><span className="si-help-label">Help</span></header>;
}
function ClubBadge({ className = '' }: { className?: string }) {
  return <span className={`si-badge-crop ${className}`} role="img" aria-label="Ashton Juniors approved fictional badge"><Image src="/templates/hollinwood-red/club-badge-ashton.png" width={1024} height={1536} priority alt=""/></span>;
}
function ProductCard({ coach = false, generic = false }: { coach?: boolean; generic?: boolean }) {
  const initials = coach ? 'CJ' : generic ? '★' : 'MR';
  const name = coach ? 'COACH JORDAN' : generic ? 'YOUR PLAYER' : 'MAYA R.';
  const detail = coach ? 'HEAD COACH' : generic ? '00 · YOUR POSITION' : '08 · MIDFIELDER';
  const label = coach ? 'Coach card artwork' : generic ? 'Generic player card example with no child identity' : 'Synthetic private player card artwork';
  return <div className={`si-product-card${generic ? ' generic' : ''}`} aria-label={label}><div className="si-card-shine"/><ClubBadge className="si-card-badge"/><span className="si-card-kicker">ASHTON JUNIORS</span><div className="si-card-avatar" aria-hidden="true">{initials}</div><strong>{name}</strong><small>{detail}</small><b>EMBLEM</b></div>;
}

export default function SquadInvitePreview() {
  const [state, setState] = useState<PreviewState>('homepage-entry');
  const [linkCopied, setLinkCopied] = useState(false);
  const index = states.findIndex(([id]) => id === state);
  const go = (offset: number) => setState(states[(index + offset + states.length) % states.length][0]);
  const reviewerAction = (label: string, next: PreviewState) => <button className="si-reviewer-action" onClick={() => setState(next)}><span>Reviewer control</span>{label} →</button>;

  const screen = useMemo(() => {
    switch (state) {
      case 'homepage-entry': return <><Hero eyebrow="Homepage · Teams" title="Create cards together — privately" copy="Invite your team with one link. Each parent creates their child’s card privately."/><div className="si-actions"><button className="si-secondary">Build several cards yourself</button><button className="si-primary" onClick={()=>setState('builder-entry')}>Create a Squad Invite</button></div><PreviewNotice/></>;
      case 'builder-entry': return <><Hero eyebrow="Start order" title="Who are you building for?" copy="Choose the route that matches how your team wants to create cards."/><FormRows rows={['Create one card','Build several cards yourself','Invite parents to create their own cards']}/><button className="si-primary" onClick={()=>setState('start')}>Create one team link <span>→</span></button></>;
      case 'start': return <><Hero eyebrow="Controlled pilot" title="Start your Squad Invite" copy="One team link lets each parent privately create their child’s card. No child information or roster is requested here."/><PreviewNotice/><button className="si-primary" onClick={()=>setState('organiser-email')}>Continue</button></>;
      case 'organiser-email': return <><Hero eyebrow="Step 1" title="Verify your organiser email" copy="We’ll verify your email before you submit team details for review."/><label className="si-field">Email address<input defaultValue="jordan.organiser@example.test" type="email"/></label><p className="si-help">Email control does not verify club authority, employment, background-check status or safeguarding clearance.</p><button className="si-primary" onClick={()=>setState('organiser-otp')}>Send verification code</button></>;
      case 'organiser-otp': return <><Hero eyebrow="Step 2" title="Enter your verification code" copy="Use the one-time code sent to the synthetic address."/><label className="si-field">Six-digit code<input defaultValue="123456" inputMode="numeric"/></label><p className="si-help">Resend available in 60 seconds · Change email</p><button className="si-primary" onClick={()=>setState('organiser-form')}>Verify email</button></>;
      case 'organiser-form': return <><Hero eyebrow="Step 3" title="Organiser and team details" copy="No child names, photographs, roster files, parent contacts, DOB, school or medical information."/><CreationFields/><FormRows rows={['Organiser: Coach Jordan','Role: Coach or authorised club representative','Delivery recipient: Coach Jordan','UK team delivery confirmed','Optional badge: synthetic approved reference']}/><button className="si-primary" onClick={()=>setState('organiser-declarations')}>Continue</button></>;
      case 'organiser-declarations': return <><Hero eyebrow="Step 4" title="Separate declarations" copy="Each acknowledgement is recorded separately with its policy version."/><div className="si-permissions"><Check text="I am an adult authorised to create and share this Squad Invite."/><Check text="The delivery recipient agrees to receive and distribute the team package."/><Check text="Each parent decides independently whether to participate."/><Check text="Emblem staff must approve this request before sharing."/></div><button className="si-primary" onClick={()=>setState('organiser-review')}>Review request</button></>;
      case 'organiser-review': return <><Hero eyebrow="Step 5" title="Review your request" copy="Edit the organiser, team, deadline and delivery-recipient details before submission."/><CreationFields/><button className="si-primary" onClick={()=>setState('request-received')}>Submit for Emblem review</button></>;
      case 'request-received': return <><div className="si-success-mark">✓</div><Hero eyebrow="Submitted for review" title="Your Squad Invite request has been received" copy="We aim to review controlled-pilot requests within two business days."/><Pill>Reference SI-SYNTHETIC</Pill><p className="si-help">Notification saved to disabled test outbox. No email was sent.</p>{reviewerAction('Open staff queue','staff-queue')}</>;
      case 'staff-queue': return <><Hero eyebrow="Staff OS · Player Queue" title="Squad Invites" copy="Separate operational queue; no child or participant records."/><div className="si-grid"><Metric value="2" label="New"/><Metric value="1" label="Under review"/><Metric value="1" label="Overdue"/><Metric value="0" label="Active"/></div><FormRows rows={['SI-SYNTHETIC · Ashton Juniors U10 · New · due within SLA','SI-DEMO-002 · Riverside U11 · Changes requested','SI-DEMO-003 · Northfield U9 · Overdue']}/>{reviewerAction('Review Squad Invite','staff-review')}</>;
      case 'staff-review': return <><Hero eyebrow="Authorised reviewer" title="Review Squad Invite" copy="Email control verified; declared role reviewed separately."/><StaffChecklist/><FormRows rows={['Badge status: Pending staff decision','Delivery recipient: Complete; address deferred','Duplicate active campaign: None found','Restricted note: Staff only','Audit history: Submitted → Under review']}/><div className="si-actions"><button className="si-secondary" onClick={()=>setState('changes-requested')}>Request changes</button><button className="si-primary" onClick={()=>setState('approval-foundation')}>Approve</button></div></>;
      case 'changes-requested': return <><Hero eyebrow="Changes requested" title="Please clarify the badge source" copy="The organiser sees this explanation, never the restricted staff note."/><Pill tone="amber">Changes requested</Pill><button className="si-primary" onClick={()=>setState('organiser-correction')}>Open organiser correction</button></>;
      case 'organiser-correction': return <><Hero eyebrow="Organiser correction" title="Update and resubmit" copy="Only permitted request fields can be changed. Existing declarations remain versioned."/><CreationFields/><Check text="I confirm the updated information is accurate."/><button className="si-primary" onClick={()=>setState('staff-review')}>Resubmit for review</button></>;
      case 'approval-foundation': return <><Hero eyebrow="Approver permission required" title="Squad Invite approved" copy="The design creates setup-required campaign state, ownership, a paused parent-link reservation, audit and one disabled outbox event in one database operation."/><Pill tone="amber">STATICALLY VERIFIED ONLY · NOT EXECUTED</Pill>{reviewerAction('Preview approval email','approval-email')}</>;
      case 'approval-email': return <><Hero eyebrow="Disabled email preview" title="Your Emblem Squad Invite link is ready" copy="Your request has been approved. Open your authenticated organiser page to finish delivery setup."/><div className="si-unavailable">Delivery mode: disabled_test · No email sent</div><p className="si-help">No parent link, child data, delivery address, internal UUID or restricted note appears in this email.</p><button className="si-primary" onClick={()=>setState('setup-required')}>Open organiser page</button></>;
      case 'setup-required': return <><Hero eyebrow="Approved" title="Delivery setup required" copy="Complete private adult fulfilment details before the parent invitation can become active."/><Pill tone="amber">approved_setup_required</Pill><PreviewNotice/><button className="si-primary" onClick={()=>setState('delivery-setup')}>Complete delivery setup</button></>;
      case 'delivery-setup': return <><Hero eyebrow="Private organiser setup" title="Team delivery details" copy="Hidden from parents, public pages, lifecycle emails and general logs."/><FormRows rows={['Adult delivery address: 10 Example Road','Postcode: EX1 2AB','Courier contact: 07000 000000','Instructions: Leave blank unless needed']}/><button className="si-primary" onClick={()=>setState('link-ready')}>Complete setup and activate</button></>;
      case 'link-ready': return <><Hero eyebrow="Active" title="Your Squad Invite link is ready" copy="The raw link is returned once after server-authoritative activation; only its hash is stored."/><div className="si-link-ready"><span className="si-icon">✓</span><div><strong>Parent-facing link ready to copy</strong><span>No participant identities or private records are exposed.</span></div></div><p className="si-help">Lost-response recovery rotates to a new credential; the old raw token cannot be reconstructed.</p></>;
      case 'notification-failure': return <><Hero eyebrow="Staff operation" title="Notification needs attention" copy="No provider call occurs. Resend preparation reuses the same outbox event and remains disabled_test."/><Pill tone="red">Failed / disabled</Pill><button className="si-secondary">Prepare audited test resend</button><p className="si-help">Synthetic action only — no mutation and no email.</p></>;
      case 'feature-disabled': return <><Hero eyebrow="Fail closed" title="Squad Invite is unavailable" copy="The runtime MVP flag defaults off and always returns unavailable in production."/><div className="si-unavailable">404 · Feature disabled</div><p className="si-help">Existing one-card and same-session squad journeys remain unchanged.</p></>;
      case 'create': return <><Hero eyebrow="Organiser setup" title="Create a Squad Invite" copy="One team link. Each parent creates their child’s card individually. Parents pay after the team price is confirmed."/><CreationFields/><Check text="I am an adult authorised to create and share this Squad Invite."/><button className="si-primary" onClick={() => setState('approval')}>Send for staff approval <span>→</span></button></>;
      case 'approval': return <><Hero eyebrow="Draft saved" title="Waiting for Emblem review" copy="The invitation cannot be shared until an authorised staff member approves it."/><StatusSteps active={1}/><Pill tone="amber">Awaiting staff approval</Pill>{reviewerAction('Open staff review', 'staff')}</>;
      case 'staff': return <><Hero eyebrow="Controlled pilot safeguard" title="Review Squad Invite" copy="A lightweight staff check before the organiser can share the invitation."/><StaffChecklist/><div className="si-actions"><button className="si-secondary" onClick={() => setState('approval')}>Return for changes</button><button className="si-primary" onClick={() => setState('publish')}>Approve Squad Invite</button></div></>;
      case 'publish': return <><Hero eyebrow="Approved" title="Squad Invite link ready" copy="Share one link in the existing parent WhatsApp group. It contains no child or parent information."/><div className="si-link-ready"><span className="si-icon">✓</span><div><strong>Reusable invitation link created</strong><span>Credential details stay hidden from the organiser view.</span></div></div><div className="si-actions"><button className="si-secondary" onClick={() => setLinkCopied(true)}>{linkCopied ? 'Link copied' : 'Copy link'}</button><button className="si-primary" onClick={() => setState('share')}>Share to WhatsApp</button></div><div className="si-quiet-actions"><button onClick={() => setState('links')}>Pause invitation</button><button onClick={() => setState('links')}>Replace link</button></div></>;
      case 'share': return <><Hero eyebrow="WhatsApp preview" title="Ready to share" copy="No contacts or group membership are sent to Emblem."/><div className="si-phone"><div className="si-phone-top">Ashton Juniors parents <span>•••</span></div><div className="si-message"><b>Coach Jordan</b><p>Ashton Juniors U10 has opened an Emblem Squad Invite. Create your child’s personalised sporting card privately by {dateText}. Participation is optional. Create your card now and pay after the team price is confirmed.</p><div className="si-share-card"><ClubBadge/><span><b>Join Ashton Juniors U10</b><small>2 more completed cards unlock £18.99 · One team delivery</small></span></div></div></div>{reviewerAction('Preview parent opening link', 'invite')}</>;
      case 'invite': return <><div className="si-invite-hero"><div><ClubBadge className="si-club-badge"/><Hero eyebrow="Ashton Juniors · Under 10" title="Make their moment iconic." copy="Create your child’s card now. Pay after the team price is confirmed."/></div><ProductCard generic/></div><Progress/><p className="si-estimate">Estimated squad size: 15</p><div className="si-trust"><b>Private. Secure. Parent controlled.</b><span>Participation is optional. No participant list or child photograph is public.</span></div><Delivery/><PreviewNotice/><button className="si-primary" onClick={() => setState('verify')}>Create your child’s card <span>→</span></button></>;
      case 'verify': return <><Hero eyebrow="Private parent session" title="Verify your email" copy="We’ll send a one-time code so you can return safely to this invitation."/><label className="si-field">Email address<input defaultValue="alex.taylor@example.test" type="email"/></label><button className="si-primary" onClick={() => setState('builder')}>Send verification code <span>→</span></button>{reviewerAction('Preview returning parent', 'resume')}</>;
      case 'resume': return <><Hero eyebrow="Welcome back" title="Resume your private card" copy="Your existing card was found. The shared team link never exposes your private builder."/><Pill>Private card resumed</Pill><button className="si-primary" onClick={() => setState('builder')}>Continue card <span>→</span></button></>;
      case 'builder': return <><Hero eyebrow="Private builder · Step 2 of 4" title="Create their card" copy="This information is not visible to Coach Jordan or other parents."/><div className="si-builder-layout"><ProductCard/><BuilderControls/></div><p className="si-help">Synthetic initials only. No real photograph is used. Controls demonstrate the intended journey and do not save data.</p><button className="si-primary" onClick={() => setState('permissions')}>Review before saving <span>→</span></button></>;
      case 'permissions': return <><Hero eyebrow="Parent permissions" title="Before you save the card" copy="Please confirm the following so Emblem can prepare your child’s personalised card."/><div className="si-permissions"><Check text="I am the child’s parent/guardian or have permission to submit their details."/><Check text="I have permission to use this photograph on the printed card."/><Check text="I understand the cards will be delivered together to Coach Jordan."/><Check text="I understand I am not paying today. I will receive a payment request after the team price is confirmed."/></div><button className="si-primary" onClick={() => setState('saved')}>Save my child’s card <span>→</span></button></>;
      case 'saved': return <><div className="si-success-mark">✓</div><Hero eyebrow="Card completed" title="Your child’s card is saved" copy="You have not been charged. When the invitation closes, Emblem will confirm the final team price and send you a payment request."/><Pill>Card design saved</Pill><Delivery detail="Your card will be delivered with the team order to Coach Jordan after payment and production."/><button className="si-primary" onClick={() => setState('invite')}>Done</button>{reviewerAction('Return to team invitation', 'invite')}</>;
      case 'closed': return <><Hero eyebrow="Invitation closed" title="New card starts are closed" copy="Parents who began before the deadline may finish their card during the 24-hour grace period."/><Pill tone="grey">Team price confirms after grace</Pill><Progress/><PreviewNotice/></>;
      case 'dashboard': return <><Hero eyebrow="Organiser dashboard" title="Ashton Juniors U10" copy="Aggregate progress only. No parent list, payment details or child photographs."/><div className="si-dashboard-strip"><div><span>Progress to squad price</span><strong>8 of 10</strong></div><div className="si-ring" aria-label="80 percent of squad-price target completed">80%</div></div><progress className="si-native-progress" value="8" max="10" aria-label="8 of 10 cards completed for squad price">8 of 10</progress><div className="si-grid"><Metric value="8" label="completed cards"/><Metric value="10" label="squad-price target"/><Metric value="15" label="estimated squad size"/><Metric value="£21.99" label="current price"/></div><div className="si-milestones"><b>Squad price: 2 more completed cards needed</b><span>Free coach card: Confirmed after 10 parents pay</span></div><StatusSteps active={2}/><Delivery organiser/>{reviewerAction('Preview 10 completed cards', 'squad')}</>;
      case 'squad': return <><div className="si-celebrate">SQUAD PRICE UNLOCKED</div><Hero eyebrow="Team price confirmed" title="£18.99 per card" copy="Ten distinct completed eligible cards freeze the squad price."/><div className="si-grid"><Metric value="10" label="completed cards"/><Metric value="£18.99" label="confirmed unit price"/></div><div className="si-milestones"><b>Squad price unlocked: £18.99 per card</b><span>Free coach card: Waiting for 10 successful payments</span></div><PreviewNotice/></>;
      case 'coach-pending': return <><div className="si-coach-layout"><ProductCard coach/><div><Hero eyebrow="Separate milestone" title="Free coach card pending" copy="In the future live product, the free coach card is confirmed after ten successful, non-refunded player payments."/><div className="si-grid"><Metric value="10" label="completed cards"/><Metric value="Not active" label="payment requests in preview"/></div><Pill tone="amber">Waiting for 10 successful payments</Pill></div></div></>;
      case 'coach-config': return <><Hero eyebrow="Adult card · proposed" title="Configure coach card" copy="This card never creates a child profile or Player OS account."/><div className="si-builder-layout"><ProductCard coach/><FormRows rows={['Coach Jordan', 'Role: Head coach', 'Team: Ashton Juniors U10', 'Design: Emblem black']}/></div><Pill tone="amber">Synthetic configuration · not production eligible</Pill>{reviewerAction('Preview fulfilment view', 'fulfilment')}</>;
      case 'fulfilment': return <><Hero eyebrow="Consolidated fulfilment" title="One team package" copy="One standard UK team delivery is included. Paid cards are individually sealed for private distribution."/><div className="si-box-visual"><b>EMBLEM</b><span>ASHTON JUNIORS U10</span><small>15 sealed card envelopes · one organiser delivery</small></div><div className="si-package"><b>Package SI-014</b><span>For the parent/guardian of Maya R. — No. 8</span><Pill>Sealed</Pill></div><p className="si-help">No email, phone, address, permission record, internal child ID or NFC claim secret appears here.</p></>;
      case 'links': return <><Hero eyebrow="Reusable link controls" title="This invitation is unavailable" copy="Invalid, expired, paused and revoked links use the same privacy-preserving response."/><div className="si-unavailable">Link unavailable</div><div className="si-link-grid">{[['Invalid', 'Unavailable'], ['Expired', 'Unavailable'], ['Paused', 'Unavailable'], ['Revoked', 'Unavailable'], ['Replaced', 'Old link unavailable']].map(([a, b]) => <div key={a}><b>{a} link</b><span>{b}</span></div>)}</div><button className="si-secondary" onClick={() => setState('publish')}>Replace shared link</button><p className="si-help">Existing private cards survive replacement without retaining public-link authority.</p></>;
    }
  }, [state, linkCopied]);

  return <main className="si-preview"><div className="si-shell"><div className="si-preview-bar"><b>Synthetic product preview</b><span>· No database · No payments · No real child data</span></div><aside className="si-reviewer-nav" aria-label="Reviewer navigation — synthetic preview only"><strong>Reviewer navigation — synthetic preview only</strong><div><button onClick={() => go(-1)} aria-label="Previous synthetic preview state">←</button><select value={state} onChange={(e) => setState(e.target.value as PreviewState)} aria-label="Choose synthetic preview state">{states.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><button onClick={() => go(1)} aria-label="Next synthetic preview state">→</button></div></aside><div className="si-product-surface"><BrandHeader/><section className="si-screen" aria-label={states[index][1]}>{screen}</section><footer className="si-footer"><span className="si-footer-identity">© Emblem</span><span>Privacy</span><span>Safety</span><span>Support</span></footer></div></div></main>;
}

function Hero({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <header className="si-header"><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></header>; }
function FormRows({ rows }: { rows: string[] }) { return <div className="si-rows">{rows.map((row) => <div key={row}>{row}</div>)}</div>; }
function Check({ text }: { text: string }) { return <label className="si-check"><input type="checkbox" defaultChecked/><span>{text}</span></label>; }
function Delivery({ detail = 'Paid cards arrive in one team package for Coach Jordan to distribute to participating families.', organiser = false }: { detail?: string; organiser?: boolean }) { return <div className="si-delivery"><span className="si-icon">↗</span><div><b>{organiser ? 'One standard UK team delivery is included' : 'Delivered together to your organiser'}</b><span>{detail}</span></div></div>; }
function Progress() { return <><div className="si-grid"><Metric value="8 of 10" label="cards completed"/><Metric value="£21.99" label="current price"/></div><progress className="si-native-progress" value="8" max="10" aria-label="8 of 10 cards completed for squad price">8 of 10</progress><p className="si-progress-copy">2 more completed cards unlock the £18.99 squad price</p><Pill tone="amber">Free coach card confirmed after 10 parents pay</Pill></>; }
function StatusSteps({ active }: { active: number }) { return <div className="si-steps">{['Created', 'Staff approval', 'Shared', 'Closed'].map((x, i) => <span className={i <= active ? 'done' : ''} key={x}>{x}</span>)}</div>; }
function CreationFields() { return <div className="si-form-grid"><label>Team<input defaultValue="Ashton Juniors U10"/></label><label>Age group<input defaultValue="Under 10"/></label><label>Organiser<input defaultValue="Coach Jordan"/></label><label>Invitation deadline<input defaultValue={dateText}/></label><label>Estimated squad size<input defaultValue="15" inputMode="numeric"/></label></div>; }
function BuilderControls() { return <div className="si-builder-controls"><button className="si-upload" type="button"><span aria-hidden="true">＋</span><b>Upload or replace photograph</b><small>Synthetic preview only</small></button><label>Display name<input defaultValue="Maya Reed"/></label><div className="si-two-fields"><label>Squad number<input defaultValue="8"/></label><label>Quantity<input defaultValue="1"/></label></div><label>Position<select defaultValue="Midfielder"><option>Midfielder</option><option>Goalkeeper</option><option>Defender</option><option>Forward</option></select></label><label>Card design<select defaultValue="Emblem black"><option>Emblem black</option><option>Club colour</option></select></label></div>; }
function StaffChecklist() { return <div className="si-staff-checklist">{['Organiser declaration received', 'Team and club identity appears credible', 'Badge-use authority recorded or pending', 'Delivery recipient provided', 'Deadline is reasonable', 'Duplicate campaign check completed', 'No child roster uploaded'].map((item) => <div key={item}><span aria-hidden="true">✓</span>{item}</div>)}</div>; }
