'use client';
import { useEffect,useState } from 'react';
export default function DeliverySetup({reference}:{reference:string}){
 const [csrf,setCsrf]=useState('');const [form,setForm]=useState({address:'',postcode:'',courierContact:'',instructions:''});const [result,setResult]=useState<{invitationPath:string|null;recoveryRequired:boolean}|null>(null);const [error,setError]=useState('');
 useEffect(()=>{void fetch('/api/squad-invite-organiser-auth/context',{cache:'no-store'}).then(r=>r.json()).then(x=>setCsrf(x.csrfToken));},[]);
 const submit=async()=>{setError('');const r=await fetch(`/api/squad-invite-requests/${encodeURIComponent(reference)}/activate`,{method:'POST',headers:{'Content-Type':'application/json','X-Emblem-CSRF':csrf},body:JSON.stringify(form)});const b=await r.json().catch(()=>null);if(!r.ok){setError('Delivery setup could not be completed.');return;}setResult(b);};
 if(result?.invitationPath)return <section className="mt-8 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Your Squad Invite link is ready</h2><p className="mt-3">Copy this parent-facing link now. The organiser page never reveals parent or child records.</p><input className="mt-4 block w-full rounded-xl border p-3" readOnly value={`${location.origin}${result.invitationPath}`}/><p className="mt-3 text-sm">If this one-time response is lost, staff or the organiser must rotate the link; the stored hash cannot reconstruct it.</p></section>;
 if(result?.recoveryRequired)return <p className="mt-6 rounded-xl bg-amber-50 p-4">This Squad Invite is already active, but the one-time link cannot be recovered. Use the audited link-replacement control.</p>;
 return <section className="mt-8 grid gap-4 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Complete adult delivery setup</h2><p>These details are private adult fulfilment data. They are not shown to parents or included in lifecycle email content.</p>{(['address','postcode','courierContact','instructions'] as const).map(k=><label key={k}>{k==='courierContact'?'Courier contact information':k[0].toUpperCase()+k.slice(1)}{k==='instructions'?' (optional)':''}<input className="mt-1 block w-full rounded-xl border p-3" value={form[k]} onChange={e=>setForm(x=>({...x,[k]:e.target.value}))}/></label>)}<button className="rounded-xl bg-orange-600 p-3 font-bold text-white" disabled={!csrf||!form.address||!form.postcode||!form.courierContact} onClick={submit}>Complete setup and activate link</button>{error&&<p role="alert" className="text-red-700">{error}</p>}</section>;
}
