'use client';
import { useEffect,useState } from 'react';
export default function DeliverySetup({reference}:{reference:string}){
 const [csrf,setCsrf]=useState('');const [form,setForm]=useState({address:'',postcode:'',courierContact:'',instructions:''});const [result,setResult]=useState<{invitationPath:string|null;recoveryRequired:boolean}|null>(null);const [error,setError]=useState('');const [copied,setCopied]=useState(false);
 useEffect(()=>{void fetch('/api/squad-invite-organiser-auth/context',{cache:'no-store'}).then(r=>r.json()).then(x=>setCsrf(x.csrfToken));},[]);
 const submit=async()=>{setError('');const r=await fetch(`/api/squad-invite-requests/${encodeURIComponent(reference)}/activate`,{method:'POST',headers:{'Content-Type':'application/json','X-Emblem-CSRF':csrf},body:JSON.stringify(form)});const b=await r.json().catch(()=>null);if(!r.ok){setError('Delivery setup could not be completed.');return;}setResult(b);};
 const copyLink=async()=>{if(!result?.invitationPath)return;try{await navigator.clipboard.writeText(`${location.origin}${result.invitationPath}`);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setError('Could not copy the link — copy it manually from the box above.');}};
 if(result?.invitationPath)return <section className="mt-8 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Your Squad Invite link is ready</h2><p className="mt-3 text-neutral-700">Copy this parent-facing link now. The organiser page never reveals parent or child records.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input className="block w-full rounded-xl border border-neutral-300 p-3" readOnly value={`${location.origin}${result.invitationPath}`}/><button type="button" onClick={copyLink} className="min-h-[48px] shrink-0 rounded-xl bg-orange-600 px-5 py-3 font-bold text-white transition hover:bg-orange-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-orange-600">{copied?'Copied!':'Copy link'}</button></div>{error&&<p role="alert" className="mt-2 text-sm text-red-700">{error}</p>}<p className="mt-3 text-sm text-neutral-600">If this one-time response is lost, staff or the organiser must rotate the link; the stored hash cannot reconstruct it.</p></section>;
 if(result?.recoveryRequired)return <p role="status" className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-900">This Squad Invite is already active, but the one-time link cannot be recovered. Use the audited link-replacement control.</p>;
 const FIELD_LABEL: Record<'address'|'postcode'|'courierContact'|'instructions',string>={address:'Address',postcode:'Postcode',courierContact:'Courier contact',instructions:'Instructions'};
 const FIELD_HINT: Partial<Record<'address'|'postcode'|'courierContact'|'instructions',string>>={courierContact:'A phone number or email the courier can use if there is a delivery problem.'};
 const FIELD_PLACEHOLDER: Partial<Record<'address'|'postcode'|'courierContact'|'instructions',string>>={courierContact:'Phone number or email address'};
 return <section className="mt-8 grid gap-4 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Complete adult delivery setup</h2><p className="text-neutral-700">These details are private adult fulfilment data. They are not shown to parents or included in lifecycle email content.</p>{(['address','postcode','courierContact','instructions'] as const).map(k=><label key={k} htmlFor={`delivery-${k}`} className="block"><span className="font-semibold">{FIELD_LABEL[k]}{k==='instructions'?' (optional)':''}</span>{FIELD_HINT[k]&&<span className="mt-1 block text-sm text-neutral-500">{FIELD_HINT[k]}</span>}<input id={`delivery-${k}`} className="mt-1 block w-full rounded-xl border border-neutral-300 p-3 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-orange-600" placeholder={FIELD_PLACEHOLDER[k]} value={form[k]} onChange={e=>setForm(x=>({...x,[k]:e.target.value}))}/></label>)}<button className="min-h-[48px] rounded-xl bg-orange-600 p-3 font-bold text-white transition hover:bg-orange-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-orange-600 disabled:opacity-60" disabled={!csrf||!form.address||!form.postcode||!form.courierContact} onClick={submit}>Complete setup and activate link</button>{error&&<p role="alert" className="text-red-700">{error}</p>}</section>;
}
