-- Gate 1 — server-issued, hashed, short-lived capability backing the
-- anonymous pre-order builder session (/api/render-print and
-- /api/order-assets' "normal builder" callers). Previously both routes
-- trusted a purely client-generated submissionKey (crypto.randomUUID(),
-- never verified server-side) as if it were a real credential — anyone
-- could invent any value and it would be accepted.
--
-- Same shape as the two capability patterns Squad Invite already uses
-- (squad_invite_participations.builder_token_hash, migration 0050;
-- squad_invite_links.token_hash, migration 0051): a cryptographically
-- random secret is generated in application code, only its SHA-256 hash is
-- ever persisted, the raw secret only ever travels as an httpOnly cookie,
-- and every write this capability authorises is verified against the
-- hash server-side first. This table exists because the normal (non-Squad-
-- Invite) builder flow has no equivalent of its own.
--
-- This file has been rewritten in full across four Gate 1 passes — never
-- committed or applied anywhere in any of its previous forms (confirmed
-- via `git status` showing it untracked at the start of each pass), so
-- amending it directly stays safe.
--
-- state machine: active -> finalising -> submitted | revoked | expired.
-- Only the transitions the real workflow needs exist:
--   active:      normal pre-order session; uploads/render allowed.
--   finalising:  order-enquiry has begun calling create_authoritative_order
--                for this submission — uploads/render fail closed from
--                this instant, not only once the RPC returns.
--   submitted:   the order was genuinely created. Terminal for
--                uploads/render, but order-enquiry retries of an ALREADY-
--                submitted capability are still allowed through to the RPC
--                (create_authoritative_order, migration 0048, has its own
--                content-fingerprint idempotency).
--   revoked:     explicit abandon ("start a new order") or staff recovery
--                — works by capability id alone, never the raw token.
--   expired:     computed from expires_at at verification time, not a
--                physically-transitioned state — no cleanup cron exists in
--                this pass; see the closure-pass report's documented
--                cleanup policy.
--
-- Counts/aggregate bytes are always DERIVED from builder_submission_assets
-- (count()/sum()), never separately stored, so they cannot drift.
--
-- Reservation versioning (this revision): a slot's reservation_id is a
-- fresh random uuid generated by EVERY successful reserve call — the
-- version stamp that makes concurrent-same-slot replacement safe. Without
-- it, two overlapping replacements of the same slot (upload A reserves,
-- upload B reserves before A's S3 write finishes, B's write succeeds,
-- A's write later fails and releases) could have A's release match on
-- byte VALUE alone and wrongly revert B's already-successful state — byte
-- values can coincide between two different uploads (e.g. two files
-- compressing to the same size), but a fresh random uuid never does.
-- finish_builder_submission_asset_reservation and
-- release_builder_submission_asset_slot both require the caller's
-- reservation_id to still match the row's CURRENT one before touching
-- anything; a stale caller's finish/release is a safe no-op, reported back
-- explicitly (not silently "succeeding").
create table public.builder_submission_capabilities (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique check (char_length(token_hash) = 64),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz,
  last_used_at timestamptz,
  state text not null default 'active' check (state in ('active', 'finalising', 'submitted', 'revoked', 'expired'))
);

create index builder_submission_capabilities_expires_idx
  on public.builder_submission_capabilities(expires_at)
  where state = 'active';

alter table public.builder_submission_capabilities enable row level security;
revoke all on public.builder_submission_capabilities from public, anon, authenticated;
grant select, insert, update on public.builder_submission_capabilities to service_role;

-- One row per stable logical asset slot per submission (e.g. a given
-- player's source photo, a given player's badge, the coach's photo).
-- Uploading to the SAME slot again (a genuine replacement) updates this
-- one row rather than creating a new one, which is what lets
-- reserve_builder_submission_asset_slot charge only the byte DELTA on
-- replacement instead of always adding the full new size. reservation_id
-- is nullable: null means "no reservation is currently in flight or
-- confirmed as current for this slot" (e.g. immediately after a release
-- reverted a failed attempt) — a state a slot can legitimately be in
-- without needing to know which earlier reservation last committed it.
create table public.builder_submission_assets (
  submission_id uuid not null references public.builder_submission_capabilities(id) on delete cascade,
  slot_key text not null check (char_length(slot_key) between 1 and 128),
  bytes bigint not null check (bytes >= 0),
  reservation_id uuid,
  updated_at timestamptz not null default now(),
  primary key (submission_id, slot_key)
);

alter table public.builder_submission_assets enable row level security;
revoke all on public.builder_submission_assets from public, anon, authenticated;
grant select, insert, update, delete on public.builder_submission_assets to service_role;

-- Issues a new capability row for a token whose hash was already computed
-- in application code (crypto.randomBytes-based — see
-- src/lib/squad-invite.ts's createBuilderToken, reused as-is rather than
-- duplicated). Raw tokens are never passed into or stored by Postgres.
create or replace function public.issue_builder_submission_capability(
  p_token_hash text,
  p_expires_at timestamptz
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
begin
  if p_token_hash !~ '^[a-f0-9]{64}$' then
    raise exception 'invalid token hash';
  end if;
  insert into public.builder_submission_capabilities(token_hash, expires_at)
  values (p_token_hash, p_expires_at)
  returning id into v_id;
  return v_id;
end;
$$;

-- Pure authentication/authorisation check: verifies a capability by its
-- hash and (best-effort) records that it was used. Returns the bound
-- submission id, or null on ANY failure — no matching hash, expired, or
-- not in the 'active' state (finalising/submitted/revoked all block
-- equally) — deliberately uniform so a caller can never distinguish these
-- by response shape or timing. Carries no ceiling concept itself — that is
-- reserve_builder_submission_asset_slot's job, called separately once a
-- caller also has bytes to account for (render-print has none; it calls
-- this alone).
create or replace function public.verify_and_touch_builder_submission_capability(
  p_token_hash text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
begin
  if p_token_hash !~ '^[a-f0-9]{64}$' then
    return null;
  end if;
  update public.builder_submission_capabilities
    set last_used_at = now()
    where token_hash = p_token_hash
      and state = 'active'
      and expires_at > now()
    returning id into v_id;
  return v_id;
end;
$$;

-- Atomically reserves capacity for one asset slot BEFORE the caller
-- uploads to S3 (to a reservation-specific temporary key — see the
-- closure-pass report) — reserve-then-upload, not upload-then-account, is
-- what keeps accounting correct when a replacement grows a slot past the
-- ceiling: if the S3 write happened first, the object would already
-- reflect the new (possibly rejected) size while the ledger still
-- recorded the old one.
--
-- Locks the capability row (state/expiry re-checked here too — defence in
-- depth against a capability transitioning to finalising between a
-- caller's own auth check and this call) and the slot row (if it already
-- exists) via SELECT ... FOR UPDATE, so two concurrent reservations for
-- the SAME submission always serialise rather than both reading a stale
-- count/total and both passing a ceiling check that only one should.
--
-- Every successful call stamps the row with a FRESH reservation_id
-- (gen_random_uuid()) — the version the caller must present to
-- finish_builder_submission_asset_reservation or
-- release_builder_submission_asset_slot. A later reservation for the same
-- slot always overwrites this stamp, which is exactly what makes an
-- earlier, now-stale caller's finish/release safely a no-op instead of
-- corrupting the winner's state.
--
-- p_max_count/p_max_total_bytes are supplied by the caller (this function
-- has no fixed idea of what a "reasonable" ceiling is — see
-- src/lib/builder-submission-capability.ts for the actual numbers and
-- their justification), so the same function serves any slot-based
-- capability without hardcoding policy into the database layer.
--
-- Returns (ok, previous_bytes, reservation_id): previous_bytes is null for
-- a brand-new slot, or the slot's prior size for a genuine replacement.
create or replace function public.reserve_builder_submission_asset_slot(
  p_id uuid,
  p_slot_key text,
  p_bytes bigint,
  p_max_count integer,
  p_max_total_bytes bigint
)
returns table(ok boolean, previous_bytes bigint, reservation_id uuid)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_existing_bytes bigint;
  v_current_count integer;
  v_current_total bigint;
  v_new_count integer;
  v_new_total bigint;
  v_locked uuid;
  v_new_reservation_id uuid;
begin
  if p_bytes is null or p_bytes < 0 or p_slot_key is null or char_length(p_slot_key) < 1 then
    return query select false, null::bigint, null::uuid;
    return;
  end if;

  select id into v_locked
    from public.builder_submission_capabilities
    where id = p_id and state = 'active' and expires_at > now()
    for update;
  if v_locked is null then
    return query select false, null::bigint, null::uuid;
    return;
  end if;

  select bytes into v_existing_bytes
    from public.builder_submission_assets
    where submission_id = p_id and slot_key = p_slot_key
    for update;

  select count(*), coalesce(sum(bytes), 0) into v_current_count, v_current_total
    from public.builder_submission_assets
    where submission_id = p_id;

  v_new_count := v_current_count + (case when v_existing_bytes is null then 1 else 0 end);
  v_new_total := v_current_total - coalesce(v_existing_bytes, 0) + p_bytes;

  if v_new_count > p_max_count or v_new_total > p_max_total_bytes or v_new_total < 0 then
    return query select false, v_existing_bytes, null::uuid;
    return;
  end if;

  v_new_reservation_id := gen_random_uuid();

  insert into public.builder_submission_assets(submission_id, slot_key, bytes, reservation_id)
    values (p_id, p_slot_key, p_bytes, v_new_reservation_id)
    on conflict (submission_id, slot_key) do update
      set bytes = excluded.bytes, reservation_id = excluded.reservation_id, updated_at = now();

  update public.builder_submission_capabilities set last_used_at = now() where id = p_id;

  return query select true, v_existing_bytes, v_new_reservation_id;
end;
$$;

-- Confirms whether a caller's reservation is still the CURRENT one for its
-- slot — called once the caller's S3 write (to its temporary key) has
-- succeeded, before promoting that object to the slot's final key. Locks
-- the row (FOR UPDATE) so this check can never race a concurrent reserve
-- that is simultaneously stamping a newer reservation_id onto it — the
-- caller either observes the write it's racing against (and correctly
-- learns it's stale) or observes a state strictly before it (and correctly
-- learns it's still current), never an inconsistent in-between. Read-only
-- otherwise: the byte accounting was already committed by reserve itself,
-- this only ever answers "is my object still the one that should exist at
-- the final key".
create or replace function public.finish_builder_submission_asset_reservation(
  p_id uuid,
  p_slot_key text,
  p_reservation_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_current uuid;
begin
  select reservation_id into v_current
    from public.builder_submission_assets
    where submission_id = p_id and slot_key = p_slot_key
    for update;
  return v_current is not null and v_current = p_reservation_id;
end;
$$;

-- Reverses a reservation when the S3 write that was supposed to follow it
-- failed instead — a failed write must never permanently consume capacity.
-- Only takes effect when p_reservation_id still matches the row's CURRENT
-- reservation_id (an optimistic-concurrency check by identity, not by the
-- byte value — see this file's header comment for exactly why byte-value
-- matching alone is unsafe). A stale caller's release — one whose
-- reservation has since been superseded by a newer, already-finished one —
-- is a safe no-op: it can never restore stale accounting over a newer
-- confirmed value, delete a newer confirmed slot, or otherwise make the
-- ledger disagree with whichever upload actually won.
create or replace function public.release_builder_submission_asset_slot(
  p_id uuid,
  p_slot_key text,
  p_reservation_id uuid,
  p_previous_bytes bigint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_matched integer := 0;
begin
  if p_previous_bytes is null then
    delete from public.builder_submission_assets
      where submission_id = p_id and slot_key = p_slot_key and reservation_id = p_reservation_id;
    get diagnostics v_matched = row_count;
    return v_matched > 0;
  else
    update public.builder_submission_assets
      set bytes = p_previous_bytes, reservation_id = null, updated_at = now()
      where submission_id = p_id and slot_key = p_slot_key and reservation_id = p_reservation_id;
    get diagnostics v_matched = row_count;
    return v_matched > 0;
  end if;
end;
$$;

-- Atomically moves a capability from 'active' to 'finalising' right before
-- order-enquiry calls create_authoritative_order — the instant this
-- commits, verify_and_touch_builder_submission_capability and
-- reserve_builder_submission_asset_slot start refusing every further
-- upload/render call for it.
--
-- Returns the capability's state as the caller must interpret it:
--   'finalising' — just transitioned by THIS call; proceed to the RPC.
--   'submitted'  — already completed by an earlier call; still proceed —
--                  create_authoritative_order's own fingerprint-based
--                  idempotency is what actually makes this safe, not a
--                  second guard here (see this file's header comment).
--   anything else ('revoked', 'expired', or the capability doesn't exist
--   at all) — the caller must reject.
create or replace function public.begin_builder_submission_finalising(p_id uuid)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_updated uuid;
  v_state text;
begin
  update public.builder_submission_capabilities
    set state = 'finalising'
    where id = p_id and state = 'active' and expires_at > now()
    returning id into v_updated;
  if v_updated is not null then
    return 'finalising';
  end if;
  select state into v_state from public.builder_submission_capabilities where id = p_id;
  return coalesce(v_state, 'not_found');
end;
$$;

-- Completes the finalising transition: 'submitted' on success, back to
-- 'active' on a genuine failure so the customer can retry with the same
-- capability rather than being permanently locked out by one transient
-- error. A no-op outside the 'finalising' state, so calling this twice
-- (e.g. a retried, already-idempotent order-enquiry response) never does
-- anything unsafe.
create or replace function public.finish_builder_submission_finalising(p_id uuid, p_success boolean)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_success then
    update public.builder_submission_capabilities
      set state = 'submitted', revoked_at = coalesce(revoked_at, now())
      where id = p_id and state = 'finalising';
  else
    update public.builder_submission_capabilities
      set state = 'active'
      where id = p_id and state = 'finalising';
  end if;
end;
$$;

-- Explicit abandon/staff-recovery path — works by capability id alone,
-- never the raw token (staff never has or needs it). Idempotent: revoking
-- an already-revoked/submitted/expired id is a silent no-op.
create or replace function public.revoke_builder_submission_capability(p_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.builder_submission_capabilities
    set state = 'revoked', revoked_at = coalesce(revoked_at, now())
    where id = p_id and state in ('active', 'finalising');
end;
$$;

alter function public.issue_builder_submission_capability(text, timestamptz) owner to postgres;
alter function public.verify_and_touch_builder_submission_capability(text) owner to postgres;
alter function public.reserve_builder_submission_asset_slot(uuid, text, bigint, integer, bigint) owner to postgres;
alter function public.finish_builder_submission_asset_reservation(uuid, text, uuid) owner to postgres;
alter function public.release_builder_submission_asset_slot(uuid, text, uuid, bigint) owner to postgres;
alter function public.begin_builder_submission_finalising(uuid) owner to postgres;
alter function public.finish_builder_submission_finalising(uuid, boolean) owner to postgres;
alter function public.revoke_builder_submission_capability(uuid) owner to postgres;

revoke all on function public.issue_builder_submission_capability(text, timestamptz) from public, anon, authenticated;
revoke all on function public.verify_and_touch_builder_submission_capability(text) from public, anon, authenticated;
revoke all on function public.reserve_builder_submission_asset_slot(uuid, text, bigint, integer, bigint) from public, anon, authenticated;
revoke all on function public.finish_builder_submission_asset_reservation(uuid, text, uuid) from public, anon, authenticated;
revoke all on function public.release_builder_submission_asset_slot(uuid, text, uuid, bigint) from public, anon, authenticated;
revoke all on function public.begin_builder_submission_finalising(uuid) from public, anon, authenticated;
revoke all on function public.finish_builder_submission_finalising(uuid, boolean) from public, anon, authenticated;
revoke all on function public.revoke_builder_submission_capability(uuid) from public, anon, authenticated;

grant execute on function public.issue_builder_submission_capability(text, timestamptz) to service_role;
grant execute on function public.verify_and_touch_builder_submission_capability(text) to service_role;
grant execute on function public.reserve_builder_submission_asset_slot(uuid, text, bigint, integer, bigint) to service_role;
grant execute on function public.finish_builder_submission_asset_reservation(uuid, text, uuid) to service_role;
grant execute on function public.release_builder_submission_asset_slot(uuid, text, uuid, bigint) to service_role;
grant execute on function public.begin_builder_submission_finalising(uuid) to service_role;
grant execute on function public.finish_builder_submission_finalising(uuid, boolean) to service_role;
grant execute on function public.revoke_builder_submission_capability(uuid) to service_role;

comment on table public.builder_submission_capabilities is 'Server-issued capability backing the anonymous pre-order builder session; raw tokens are never persisted, only their SHA-256 hash. See this file''s header comment for the full active/finalising/submitted/revoked/expired state machine.';
comment on table public.builder_submission_assets is 'Per-slot upload ledger for one builder_submission_capabilities row — counts/aggregate bytes are always derived from this table (count()/sum()), never separately stored. reservation_id versions each slot so concurrent same-slot replacements cannot corrupt each other (see this file''s header comment).';
